<?php
$title = 'My Books';
$this->headTitle($title);
?>

<h1><?php  $this->escapeHtml($title);  ?></h1>

<p>
    <a href="<?php echo $this->url('book', array('action'=>'add'));?>">Add new Book</a>
</p>

<?php
if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach ($messages as $message) {
        echo $message;
    }

    echo '</div>';
}
?>


<table class="table">
    <tr>
        <th>Name</th>
        <th>Author</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($books as $book) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($book->name);?></td>
            <td><?php echo $this->escapeHtml($book->author);?></td>
            <td>
                <a href="<?php echo $this->url('book',
                    array('action'=>'edit', 'id' => $book->id));?>">Edit</a>

                <a href="<?php echo $this->url('book',
                    array('action'=>'delete', 'id' => $book->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
