<?php
$title = 'My Student';
$this->headTitle($title);
?>

<h1><?php  $this->escapeHtml($title);  ?></h1>

<p>
    <a href="<?php echo $this->url('student', array('action'=>'add'));?>">Add new Student</a>
</p>

<?php

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-danger">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>

<table class="table">
    <tr>
        <th>fristName</th>
        <th>lastName</th>
        <th>Address</th>
        <th>email</th>
        <th>owned books</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($students as $student) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($student->fristName);?></td>
            <td><?php echo $this->escapeHtml($student->lastName);?></td>
            <td><?php echo $this->escapeHtml($student->address);?></td>
            <td><?php echo $this->escapeHtml($student->email);?></td>
            <td>
                <?php  foreach ($student->books as $book):?>
                <?php  echo $book->name;?>
                    <a href="<?php echo $this->url('new',
                        array(
                                'action'=>'deletebook',
                            'id' =>$student->id,
                            'bookid'=>$book->id,

                        ));?>">delete</a>
                    <br><?php endforeach;?>
            </td>

            <td>
                <a href="<?php echo $this->url('student',
                    array('action'=>'edit', 'id' => $student->id));?>">Edit</a>
                <a href="<?php echo $this->url('student',
                    array('action'=>'delete', 'id' => $student->id));?>">Delete</a>

                <a href="<?php echo $this->url('student',
                    array('action'=>'addbook', 'id' => $student->id));?>">addbook</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
